### PR TITLE
Lengths of words in a sentence #4

### PR DESCRIPTION
**Pull request by ThomasMatthewEvans**
Thank you for your advice. I think I have created a PR as suggested by you. Any more help/advice will be greatly appreciated. Thank you!

### CODE REVIEW

**Review by VamsiSangam — COMMENTED** [review]
Add ``` .py ``` extension to your file. Everything else is perfect! :smile:

**Comment by VamsiSangam** [comment]
And it is a highly recommended practice to mention the issue number in your PR, so that we can efficiently keep a track of how an issue was solved. And it is also a recommended practice to name your PR exactly as its corresponding issue name, followed by the issue number. I am doing it for now :smile: 

This is for issue #4

**Comment by VamsiSangam** [comment]
You can remove the ``` #4 ``` from the file name. Referencing issue is only required in the pull request description and PR name :smile:

**Comment by VamsiSangam** [comment]
LGTM :+1:

**Comment by VamsiSangam** [comment]
Thanks for your contribution :smile:

**Comment by ThomasMatthewEvans** [comment]
Thank you for the help, I learned a lot. I think I might try 1 or 2 more and hopefully get the PR process right this time!

**Comment by VamsiSangam** [comment]
Good luck :smile:

**Pull request merged**
